import { test, expect, type Page } from '@playwright/test';
import { injectGameState } from '../helpers/game';
import { medirContraste } from '../helpers/contraste';
test.use({serviceWorkers:'block'});test.beforeEach(({},info)=>test.skip(info.project.name!=='chromium','Cenários fixam a viewport.'));
async function preparar(page:Page,gold=1250){await page.setViewportSize({width:390,height:740});await page.route('**/*',r=>new URL(r.request().url()).hostname==='localhost'?r.continue():r.abort());await page.goto('/jogar/',{waitUntil:'domcontentloaded'});await injectGameState(page,{gold});await page.emulateMedia({reducedMotion:'reduce'});}
async function abrir(page:Page,type:string){await page.locator('.mdock-btn.forge-item:visible').focus();await page.evaluate(t=>(window as any).showMobileActionConfirm(t),type);const card=page.locator('.nqcost-card');await expect(card).toBeVisible();return card;}
for(const [type,title,button,cost]of [['forge','Forjar Item','Forjar agora',300],['legendary','Forjar Lendário','Forjar lendário',1000],['chest','Abrir Baú','Abrir baú',130]]as const){
 test(type+': custo real, cancelamento sem gasto e compra pela ação original',async({page})=>{await preparar(page);let card=await abrir(page,type);await expect(card).toHaveAccessibleName(title);await expect(card.locator('.nqcost-ledger dd')).toHaveText([cost+' ouro','1250 ouro',(1250-cost)+' ouro']);expect(await page.evaluate(medirContraste,'.nqcost-card')).toEqual([]);
 for(const key of ['Tab','Tab','Shift+Tab']){await page.keyboard.press(key);expect(await card.evaluate(e=>e.contains(document.activeElement))).toBe(true);}await card.getByRole('button',{name:'Cancelar'}).click();await expect(card).toHaveCount(0);expect(await page.evaluate(()=>(0,eval)('state.gold'))).toBe(1250);await expect(page.locator('.mdock-btn.forge-item:visible')).toBeFocused();
 card=await abrir(page,type);await page.keyboard.press('Escape');await expect(card).toHaveCount(0);expect(await page.evaluate(()=>(0,eval)('state.gold'))).toBe(1250);card=await abrir(page,type);await card.getByRole('button',{name:button,exact:true}).click();await expect(card).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>(0,eval)('state.gold'))).toBe(1250-cost);if(type==='chest'){expect(await page.evaluate(()=>(0,eval)('state.chestsOpened'))).toBe(3);await expect(page.locator('#chestModal')).toHaveClass(/show/);}else await expect(page.locator('.equip-compare-overlay, .forge-popup')).toBeVisible();
 });
 test(type+': saldo insuficiente não permite gastar',async({page})=>{await preparar(page,80);const card=await abrir(page,type);await expect(card.locator('.nqcost-ledger dd')).toHaveText([cost+' ouro','80 ouro',(cost-80)+' ouro']);await expect(card.getByRole('button',{name:button,exact:true})).toBeDisabled();await expect(card.getByRole('button',{name:'Cancelar'})).toBeFocused();await page.keyboard.press('Escape');expect(await page.evaluate(()=>(0,eval)('state.gold'))).toBe(80);});
}
for(const width of [320,390,1100])test('confirmação legível e fechável com texto ampliado em '+width,async({page})=>{await preparar(page);const card=await abrir(page,'legendary');await page.setViewportSize({width,height:740});await page.evaluate(async()=>{document.documentElement.style.fontSize='32px';await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));});const overflow=await card.evaluate(el=>{const out:string[]=[];const walk=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);for(let n=walk.nextNode();n;n=walk.nextNode()){if(!n.textContent?.trim())continue;const range=document.createRange();range.selectNodeContents(n);if([...range.getClientRects()].some(r=>r.width&&(r.left<0||r.right>innerWidth+1)))out.push(n.textContent!);}return out;});expect(overflow).toEqual([]);for(const button of await card.getByRole('button').all()){const r=(await button.boundingBox())!;expect(r.height).toBeGreaterThanOrEqual(44);expect(r.y+r.height).toBeLessThanOrEqual(740);}expect(await card.evaluate(e=>getComputedStyle(e).animationName)).toBe('none');await page.keyboard.press('Escape');await expect(card).toHaveCount(0);});
test('clicar fora da confirmação fecha sem gastar',async({page})=>{await preparar(page);const card=await abrir(page,'forge');await page.waitForTimeout(150);await page.locator('.nqcost-overlay').click({position:{x:2,y:2}});await expect(card).toHaveCount(0);expect(await page.evaluate(()=>(0,eval)('state.gold'))).toBe(1250);});
