import { test, expect, type Page, type Route } from '@playwright/test';
import { injectGameState } from '../helpers/game';
import { medirContraste } from '../helpers/contraste';
test.use({serviceWorkers:'block'});test.beforeEach(({},info)=>test.skip(info.project.name!=='chromium','Cenários fixam a própria viewport.'));
async function abrir(page:Page,width=390){await page.setViewportSize({width,height:740});await page.route('**/*',r=>new URL(r.request().url()).hostname==='localhost'?r.continue():r.abort());await page.goto('/jogar/',{waitUntil:'domcontentloaded'});await injectGameState(page);await page.emulateMedia({reducedMotion:'reduce'});const origin=page.locator('#forgeBtn:visible,.mdock-btn.forge-item:visible').first();await origin.focus();await page.evaluate(()=>(0,eval)('flagQuestion()'));const card=page.locator('.nqflag-card');await expect(card).toBeVisible();return {card,origin};}
test('relato mantém o contexto e fecha sem enviar',async({page})=>{const {card,origin}=await abrir(page);await expect(card).toHaveAccessibleName('Sinalizar erro na questão');await expect(card.locator('blockquote')).toHaveText(await page.evaluate(()=>(0,eval)('state.current.q.substring(0,300)')));await expect(card.locator('#flagComment')).toBeFocused();expect(await page.evaluate(medirContraste,'.nqflag-card')).toEqual([]);for(const key of ['Tab','Tab','Shift+Tab']){await page.keyboard.press(key);expect(await card.evaluate(e=>e.contains(document.activeElement))).toBe(true);}await card.getByRole('button',{name:'Cancelar'}).click();await expect(card).toHaveCount(0);await expect(origin).toBeFocused();await page.evaluate(()=>(0,eval)('flagQuestion()'));await expect(card).toBeVisible();await page.keyboard.press('Escape');await expect(card).toHaveCount(0);});
test('todas as categorias seguem no payload e falha permite nova tentativa',async({page})=>{const {card}=await abrir(page);const bodies:any[]=[];await page.route('**/functions/v1/send-flag',r=>{bodies.push(r.request().postDataJSON());return r.fulfill({status:502,json:{success:false}})});const labels=['Resposta incorreta','Desatualizada','Ambígua','Erro de texto','Outra'];for(const [i,label]of labels.entries()){await card.getByRole('radio',{name:label,exact:true}).check();await card.locator('#flagComment').fill('Comentário de teste local');await card.getByRole('button',{name:/Enviar/}).click();await expect.poll(()=>bodies.length).toBe(i+1);await expect(card.locator('#flagStatus')).toContainText('Falha ao enviar (502)');expect(bodies[i].subject).toContain(label);expect(bodies[i].message).toContain('Comentário de teste local');await expect(card.locator('#flagSendBtn')).toBeEnabled();}});
test('Outra exige comentário e não inicia envio inválido',async({page})=>{const {card}=await abrir(page);let requests=0;await page.route('**/functions/v1/send-flag',r=>{requests++;return r.abort()});await card.getByRole('radio',{name:'Outra',exact:true}).check();await card.locator('#flagComment').fill('curto');await card.locator('#flagSendBtn').click();await expect(card.locator('#flagStatus')).toContainText('mín. 10 caracteres');expect(requests).toBe(0);});
test('sem conexão conserva o comentário e permite cancelar',async({page,context})=>{const {card}=await abrir(page);await card.locator('#flagComment').fill('Comentário preservado offline');await context.setOffline(true);await card.locator('#flagSendBtn').click();await expect(card.locator('#flagStatus')).toContainText('Sem conexão');await expect(card.locator('#flagComment')).toHaveValue('Comentário preservado offline');await context.setOffline(false);});
test('envio pendente bloqueia repetição e sucesso fecha o formulário',async({page})=>{const {card}=await abrir(page);let pending:Route|undefined;await page.route('**/functions/v1/send-flag',r=>{pending=r});await card.locator('#flagSendBtn').click();await expect.poll(()=>!!pending).toBe(true);await expect(card.locator('#flagSendBtn')).toBeDisabled();await expect(card.locator('#flagSendBtn')).toHaveText('Enviando...');await pending!.fulfill({json:{success:true}});await expect(card.locator('#flagStatus')).toContainText('Erro enviado');await expect(card).toHaveCount(0);});
for(const width of [320,390,1100])test('rótulos dentro de cada opção com texto ampliado em '+width,async({page})=>{const {card}=await abrir(page,width);for(const size of [16,32]){await page.evaluate(async size=>{document.documentElement.style.fontSize=size+'px';await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));},size);expect(await card.locator('.nqflag-category').evaluateAll(labels=>labels.every(e=>{const box=e.getBoundingClientRect(),range=document.createRange();range.selectNodeContents(e.querySelector('span')!);return [...range.getClientRects()].every(r=>r.left>=box.left&&r.right<=box.right-10)}))).toBe(true);for(const button of await card.getByRole('button').all()){const r=(await button.boundingBox())!;expect(r.height).toBeGreaterThanOrEqual(44);expect(r.y+r.height).toBeLessThanOrEqual(740);}const region=card.getByRole('region');await region.focus();await page.keyboard.press('End');await expect.poll(()=>region.evaluate(e=>e.scrollHeight<=e.clientHeight||e.scrollTop>0)).toBe(true);}await card.getByRole('radio',{name:'Desatualizada',exact:true}).check();await expect(card.getByRole('radio',{name:'Desatualizada',exact:true})).toBeChecked();});
