import {test,expect,type Page} from '@playwright/test';
import {injectGameState} from '../helpers/game';
import {medirContraste} from '../helpers/contraste';
test.use({serviceWorkers:'block'});
test.beforeEach(({},info)=>test.skip(info.project.name!=='chromium','Cenários fixam a própria viewport.'));
async function abrir(page:Page,width=390){await page.setViewportSize({width,height:740});await page.route('**/*',r=>new URL(r.request().url()).hostname==='localhost'?r.continue():r.abort());await page.goto('/jogar/',{waitUntil:'domcontentloaded'});await injectGameState(page);await page.emulateMedia({reducedMotion:'reduce'});const origin=page.locator('#forgeBtn:visible,.mdock-btn.forge-item:visible').first();await origin.focus();await page.evaluate(()=>(0,eval)(`_showResumoModal({label:'Título <seguro>',autores:'Autor & equipe',jornal:'Revista <fonte>',ano:2001,resumo:'Resumo integral. '.repeat(35),conclusao:'Conclusão preservada',curiosidade:'Curiosidade preservada',impacto:'Impacto preservado'})`));return {card:page.locator('.nqreader-card'),origin};}
test('leitor preserva seções e escapa metadados, com foco e contraste',async({page})=>{const {card,origin}=await abrir(page);await expect(card).toHaveAccessibleName('Título <seguro>');await expect(card.locator('h3')).toHaveText(['Resumo','Conclusão principal','Curiosidade','Impacto na nefrologia']);await expect(card.locator('.nqreader-reference')).toHaveText('Autor & equipeRevista <fonte>');expect(await page.evaluate(medirContraste,'.nqreader-card')).toEqual([]);await expect(card.getByRole('button',{name:'Fechar'})).toBeFocused();for(const key of ['Tab','Tab','Shift+Tab']){await page.keyboard.press(key);expect(await card.evaluate(e=>e.contains(document.activeElement))).toBe(true);}await page.keyboard.press('Escape');await expect(card).toHaveCount(0);await expect(origin).toBeFocused();});
test('seções ausentes e resumo em elaboração não inventam conteúdo',async({page})=>{const {card}=await abrir(page);await page.evaluate(()=>(0,eval)(`_showResumoModal({label:'Parcial',impacto:'Somente impacto'})`));await expect(card.locator('h3')).toHaveText(['Impacto na nefrologia']);await expect(card.locator('.nqreader-reference')).toHaveCount(0);await page.evaluate(()=>(0,eval)(`_showResumoModal({label:'Em elaboração'})`));await expect(card.locator('.nqreader-empty')).toHaveText('Resumo em elaboração — disponível em breve.');await card.getByRole('button',{name:'Fechar'}).click();await expect(card).toHaveCount(0);});
for(const width of [320,390,1100])test('leitura completa e fechar acessível em '+width,async({page})=>{const {card}=await abrir(page,width);for(const size of [16,32]){await page.evaluate(async size=>{document.documentElement.style.fontSize=size+'px';await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));},size);expect(await card.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);expect(await card.locator('h2,h3,p').evaluateAll(nodes=>nodes.every(e=>{const range=document.createRange();range.selectNodeContents(e);return [...range.getClientRects()].every(r=>r.left>=0&&r.right<=innerWidth)}))).toBe(true);const button=card.getByRole('button',{name:'Fechar'});const r=(await button.boundingBox())!;expect(r.height).toBeGreaterThanOrEqual(44);expect(r.y+r.height).toBeLessThanOrEqual(740);const region=card.getByRole('region');await region.focus();await page.keyboard.press('End');await expect.poll(()=>region.evaluate(e=>e.scrollHeight<=e.clientHeight||e.scrollTop>0)).toBe(true);}await page.screenshot({path:'C:/Users/orlan/.codex/visualizations/2026/09/29/01a0ee14-d784-7182-9cae-4b085e4bb94b/resumo-integrado-'+width+'.png'});});
