import { test, expect, type Page } from '@playwright/test';
import { injectGameState } from '../helpers/game';
import { medirContraste } from '../helpers/contraste';
test.use({serviceWorkers:'block',reducedMotion:'reduce'});
async function preparar(page:Page){await page.route('**/*',r=>new URL(r.request().url()).hostname==='localhost'?r.continue():r.abort());await page.goto('/jogar/',{waitUntil:'domcontentloaded'});await injectGameState(page);await page.waitForLoadState('load');await page.locator('#forgeBtn:visible, .mdock-btn.forge-item:visible').first().focus();}
async function abrir(page:Page){await preparar(page);await page.evaluate(()=>(0,eval)('showExtraLifeModal()'));return page.locator('.nqlife-card');}
test('vida extra informa o ganho, mantém foco e não altera estado ao fechar',async({page})=>{const card=await abrir(page);await expect(page.getByRole('dialog',{name:'+1 vida'})).toBeVisible();await expect(card.locator('.nqlife-celebration')).toHaveText('Os Deuses do Néfron reconhecem sua dedicação!');await expect(card.locator('.nqlife-description')).toHaveText('Continue sua jornada com renovada energia e sabedoria.');const button=card.getByRole('button',{name:'Continuar'});await expect(button).toBeFocused();expect((await button.boundingBox())!.height).toBeGreaterThanOrEqual(48);const before=await page.evaluate(()=>(0,eval)('JSON.stringify(state)'));for(const key of ['Tab','Tab','Shift+Tab']){await page.keyboard.press(key);expect(await card.evaluate(e=>e.contains(document.activeElement))).toBe(true);}if(process.env.NQ_CAPTURE_DIR)await page.screenshot({path:process.env.NQ_CAPTURE_DIR+'/vida-extra-integrada-'+test.info().project.name+'.png'});await button.click();await expect(card).toHaveCount(0);await expect(page.locator('#forgeBtn:visible, .mdock-btn.forge-item:visible').first()).toBeFocused();expect(await page.evaluate(()=>(0,eval)('JSON.stringify(state)'))).toBe(before);});
test('regra concede apenas uma vida e respeita o máximo',async({page})=>{await preparar(page);await page.evaluate(()=>(0,eval)('state.level=5;state.lives=2;state.extraLifeGiven=false;checkExtraLife();checkExtraLife()'));expect(await page.evaluate(()=>(0,eval)('state.lives'))).toBe(3);await expect(page.locator('.extra-life-popup')).toHaveCount(1);await page.keyboard.press('Escape');await expect(page.locator('.extra-life-popup')).toHaveCount(0);await page.evaluate(()=>(0,eval)('state.lives=effectiveMaxLives();state.extraLifeGiven=false;checkExtraLife()'));expect(await page.evaluate(()=>(0,eval)('state.lives===effectiveMaxLives()'))).toBe(true);await expect(page.locator('.extra-life-popup')).toHaveCount(0);});
for(const width of [320,390])test('vida extra completa a 200% em '+width,async({page})=>{await page.setViewportSize({width,height:700});const card=await abrir(page);await page.evaluate(()=>document.documentElement.style.fontSize='32px');const r=(await card.getByRole('button',{name:'Continuar'}).boundingBox())!;expect(r.x).toBeGreaterThanOrEqual(0);expect(r.x+r.width).toBeLessThanOrEqual(width);expect(r.y+r.height).toBeLessThanOrEqual(700);expect(r.height).toBeGreaterThanOrEqual(48);expect(await card.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);const reading=card.getByRole('region');await reading.focus();await page.keyboard.press('End');expect(await reading.evaluate(e=>e.scrollTop+e.clientHeight>=e.scrollHeight-1)).toBe(true);expect(await page.evaluate(medirContraste,'.extra-life-popup')).toEqual([]);await page.emulateMedia({reducedMotion:'reduce'});expect(await card.locator('.nqlife-fill').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');if(process.env.NQ_CAPTURE_DIR)await page.screenshot({path:process.env.NQ_CAPTURE_DIR+'/vida-extra-integrada-'+width+'-200.png'});});
test('iluminação breve termina sem pulsação contínua',async({page})=>{const card=await abrir(page);await page.emulateMedia({reducedMotion:'no-preference'});const fill=card.locator('.nqlife-fill');expect(await fill.evaluate(e=>getComputedStyle(e).animationIterationCount)).toBe('1');await expect.poll(()=>fill.evaluate(e=>getComputedStyle(e).opacity)).toBe('0.15');});
