import { test, expect, type Page } from '@playwright/test';
import { injectGameState } from '../helpers/game';
test.use({serviceWorkers:'block'});
async function preparar(page:Page){await page.route('**/*',r=>new URL(r.request().url()).hostname==='localhost'?r.continue():r.abort());await page.goto('/jogar/',{waitUntil:'domcontentloaded'});await injectGameState(page,{gold:0});await page.waitForLoadState('load');await page.evaluate(()=>{(window as any).authUser={id:'oracle-test',app_metadata:{premium:true}};(window as any).getAuthToken=async()=>null;});}
async function responder(page:Page,correct=true){const index=await page.evaluate(correct=>(0,eval)(correct?'state.current.a':'(state.current.a+1)%state.current.o.length'),correct);await page.locator('#options .option[data-idx="'+index+'"]').click();await expect(page.locator('#nextBtn')).toBeVisible();}
async function abrir(page:Page){await page.evaluate(()=>(window as any).openOraculoFromJourney());await expect(page.locator('#mentorPanel')).toBeVisible();}
async function proxima(page:Page){await page.locator('#nextBtn').click();await expect.poll(()=>page.evaluate(()=>(0,eval)('state.answered'))).toBe(false);await expect(page.locator('#mentorPanel')).toHaveCount(0);}
for(const correct of [true,false])test('próxima pergunta fecha e bloqueia Oráculo após '+(correct?'acerto':'erro'),async({page})=>{await preparar(page);let calls:any[]=[];await page.route('**/functions/v1/ai-mentor',r=>{calls.push(r.request().postDataJSON());return r.fulfill({json:{reply:'Resposta de teste'}})});await responder(page,correct);await abrir(page);await page.locator('#mentorInput').fill('Dúvida de teste');await page.locator('#mentorInput').press('Enter');await expect(page.locator('#mentorChat')).toContainText('Resposta de teste');expect(calls).toHaveLength(1);await proxima(page);
 await page.evaluate(()=>{(window as any).openMentorModal();(window as any)._sendMentorMessage();});await expect(page.locator('#mentorPanel')).toHaveCount(0);expect(calls).toHaveLength(1);await page.evaluate(()=>(window as any).openOraculoFromJourney());await expect(page.locator('#oracleAnswerFirstPopup')).toBeVisible();await page.locator('#oracleAnswerFirstPopup [data-remove-id]').last().click();
 const text=await page.locator('#question').textContent();await responder(page);await abrir(page);await page.locator('#mentorInput').fill('Outra dúvida de teste');await page.locator('#mentorInput').press('Enter');await expect.poll(()=>calls.length).toBe(2);expect(calls[1].questionText).toBe(text);expect(calls[1].history).toEqual([]);
});
test('avançar enquanto autenticação aguarda não envia consulta da carta antiga',async({page})=>{await preparar(page);let calls=0;await page.route('**/functions/v1/ai-mentor',r=>{calls++;return r.fulfill({json:{reply:'Resposta'}})});await responder(page);await abrir(page);await page.evaluate(()=>{(window as any).getAuthToken=()=>new Promise(resolve=>{(window as any).releaseOracleAuth=resolve});});await page.locator('#mentorInput').fill('Dúvida pendente');await page.locator('#mentorInput').press('Enter');await expect.poll(()=>page.evaluate(()=>typeof (window as any).releaseOracleAuth)).toBe('function');await proxima(page);await page.evaluate(async()=>{(window as any).releaseOracleAuth(null);await new Promise(resolve=>setTimeout(resolve,0));});expect(calls).toBe(0);await expect(page.locator('#mentorPanel')).toHaveCount(0);});
test('resposta tardia não reaparece nem entra no histórico da questão seguinte',async({page})=>{await preparar(page);await page.evaluate(()=>{const original=window.fetch;let first=true;(window as any).oracleBodies=[];window.fetch=async(url,init)=>{if(!String(url).includes('/ai-mentor'))return original(url,init);(window as any).oracleBodies.push(JSON.parse(String(init?.body)));if(first){first=false;return new Promise(resolve=>{(window as any).releaseOracleReply=()=>resolve(new Response(JSON.stringify({reply:'RESPOSTA ANTIGA'}),{status:200,headers:{'Content-Type':'application/json'}}))})}return new Response(JSON.stringify({reply:'Resposta nova'}),{status:200,headers:{'Content-Type':'application/json'}});};});await responder(page);await abrir(page);await page.locator('#mentorInput').fill('Dúvida antiga');await page.locator('#mentorInput').press('Enter');await expect.poll(()=>page.evaluate(()=>typeof (window as any).releaseOracleReply)).toBe('function');await proxima(page);await responder(page);await abrir(page);await page.evaluate(async()=>{(window as any).releaseOracleReply();await new Promise(resolve=>setTimeout(resolve,0));});await expect(page.locator('#mentorChat')).not.toContainText('RESPOSTA ANTIGA');await page.locator('#mentorInput').fill('Dúvida nova');await page.locator('#mentorInput').press('Enter');await expect(page.locator('#mentorChat')).toContainText('Resposta nova');const bodies=await page.evaluate(()=>(window as any).oracleBodies);expect(bodies[1].history).toEqual([]);expect(bodies[1].questionText).toBe(await page.locator('#question').textContent());});
